Milestone-master/ANAComputeRegisterPage/src/controllers/NavigationController.java
package controllers;

import javax.faces.bean.ManagedBean;


@ManagedBean
public class NavigationController {
	
	public String onSubmit(String desiredLocation) {
		if (getLoggedName() == null || getLoggedName() == "Not Logged In") {
			desiredLocation = "Login.xhtml?faces-redirect=true";
		}
		return desiredLocation;
	}
	
	public String adminOnSubmit(String desiredLocation) {
		if (LoginController.loggedUser.isAdmin() == false) {
			desiredLocation = "Home.xhtml?faces-redirect=true";
		}
		//System.out.println("Send to " + desiredLocation);
		return desiredLocation;
	}
	
	
	public String getLoggedName() {
		//System.out.println(LoginController.loggedUser.getUsername());
		String sendUsernName = "Not Logged In";
		if (LoginController.loggedUser.getUsername() != null && LoginController.loggedUser.getUsername() != "") {
			sendUsernName = LoginController.loggedUser.getUsername();
			return "Logged in as: " + sendUsernName;
		} 
		return sendUsernName;
	}

}

Milestone-master/ANAComputeRegisterPage/WebContent/layouts/commonContent.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns= "http://www.w3.org/1999/xhtml"
	  xmlns:ui="http://java.sun.com/jsf/facelets"
	  xmlns:f="http://java.sun.com/jsf/core"
	  xmlns:h="http://java.sun.com/jsf/html">
	  
	  <ui:composition>
	 <h:outputStylesheet library="css" name="style.css"></h:outputStylesheet>
	  <link rel="stylesheet" href="css/style.css" type="text/css" />
	  
	  </ui:composition>
	  
	  
</html>

Milestone-master/ANAComputeRegisterPage/WebContent/layouts/commonFooter.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<ui:composition>
	<h:outputStylesheet library="css" name="style.css"></h:outputStylesheet>
	<link rel="stylesheet" href="css/style.css" type="text/css" />
	<h:form class="bottom">
		<h4></h4>

	</h:form>
</ui:composition>


</html>

Milestone-master/ANAComputeRegisterPage/WebContent/layouts/commonHeader.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<ui:composition>
	<h:outputStylesheet library="css" name="style.css"></h:outputStylesheet>
	<link rel="stylesheet" type="text/css" href="style.css" media="all" />



	<body>
	<h:commandButton
				action="#{navigationController.onSubmit('Home.xhtml')}"
				class="some_class" />
		<div class="navigation">
			<nav>
			<ul>
				<li><a href="#{navigationController.onSubmit('Home.xhtml')}">Home</a></li>
				<li><a href="Login.xhtml">Login</a></li>
				<li><a href="CreateAccount.xhtml">Register</a></li>
				<li><a href="#{navigationController.onSubmit('Products.xhtml')}">Products</a></li>
				<li><a href="#">Contact</a></li>
			</ul>
			</nav>
			<div class="loginHeader">
				<font color="black">
					#{navigationController.loggedName}</font>
			</div>
		</div>
		
	</body>


</ui:composition>



</html>

Milestone-master/ANAComputeRegisterPage/WebContent/layouts/commonLayouts.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns= "http://www.w3.org/1999/xhtml"
	  xmlns:ui="http://java.sun.com/jsf/facelets"
	  xmlns:f="http://java.sun.com/jsf/core"
	  xmlns:h="http://java.sun.com/jsf/html">
	  
	  <h:head>
	 
	  </h:head>
	  <h:body>
	   <h:outputStylesheet library = "css" name = "css/style.css"></h:outputStylesheet>
	   <link rel="stylesheet" href="css/style.css" type="text/css" />
	   <h:body style="background-repeat: no-repeat">
			</h:body>
	  	<div id = "page">
	  		<div id = "header">
	  			<ui:insert name = "header">
	  				<ui:include src="/layouts/commonHeader.xhtml" />
	  			</ui:insert>
	  		</div>
	  		<div id = "content">
	  			  	<ui:insert name = "content">
	  				<ui:include src="/layouts/commonContent.xhtml" />
	  			</ui:insert></div>
	  		<div id = "footer">
	  			  	<ui:insert name = "footer">
	  				<ui:include src="/layouts/commonFooter.xhtml" />
	  			</ui:insert></div>
	  	
	  	</div>
	  
	  </h:body>
	  
	  
	  
</html>